# Generated by Django 4.1.5 on 2023-02-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_post',
            field=models.CharField(max_length=60),
        ),
    ]
